# -*- coding: utf-8 -*-
"""mini project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ui5mCEJ9YGhvxcpHbwctPzhGfH0L7n7k
"""

import pandas as pd
import plotly.express as px

df = pd.read_csv('OnlineRetail.csv', encoding='latin-1')
df.head()

df = df.dropna(subset=['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'UnitPrice', 'Country'])
df = df[(df['Quantity'] > 0) & (df['UnitPrice'] > 0)]
df['Revenue'] = df['Quantity'] * df['UnitPrice']

print(df.describe())

print(df.isnull().sum())

print(df.head())
print(df.info())

"""حساب إجمالي الإيرادات لكل دولة

نعمل تجميع حسب الدولة ونحسب مجموع Revenue
"""

revenue_country = df.groupby('Country')['Revenue'].sum().sort_values(ascending=False)
revenue_country

"""أعلى 10 منتجات حسب الإيرادات

نعمل تجميع حسب الوصف (Description)، ثم نأخذ أعلى 10.
"""

top_products = df.groupby('Description')['Revenue'].sum().sort_values(ascending=False).head(10)
top_products

import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))
top_products.plot(kind='bar', color='orange')
plt.title('Top 10 Products by Revenue')
plt.ylabel('Revenue')
plt.xlabel('Product')
plt.xticks(rotation=45)
plt.show()

"""متوسط حجم السلة (متوسط كمية المشتريات لكل فاتورة)

تجميع حسب رقم الفاتورة، جمع الكميات، ثم أخذ المتوسط
"""

basket_size = df.groupby('InvoiceNo')['Quantity'].sum()
avg_basket_size = basket_size.mean()
avg_basket_size

print(f"Average Basket Size (Quantity per Invoice): {avg_basket_size:.2f}")

fig = px.histogram(
    basket_size,
    title="Distribution of Basket Sizes",
    labels={"value": "Items per Invoice"}
)
fig.show()

df = pd.DataFrame({
    "Category": ["A", "B", "C", "D"],
    "Value": [10, 20, 15, 30]
})
fig = px.bar(df, x="Category", y="Value", title="Bar Chart using Plotly")
fig.show()

df = pd.DataFrame({
    "Day": [1, 2, 3, 4, 5],
    "Sales": [100, 120, 90, 150, 180]
})

fig = px.line(df, x="Day", y="Sales", title="Sales Over Time")
fig.show()

df = {
    "Labels": ["Apple", "Samsung", "Xiaomi"],
    "Share": [40, 35, 25]
}

fig = px.pie(df, names="Labels", values="Share", title="Market Share")
fig.show()

df = pd.DataFrame({
    "x": [1,2,3,4,5],
    "y": [3,7,1,9,5]
})

fig = px.scatter(df, x="x", y="y", title="Scatter Plot Example")
fig.show()

df = {"values": [10,20,20,30,40,40,40,50,60]}

fig = px.histogram(df, x="values", title="Histogram Example")
fig.show()